Models/MeetingInfo.cs
namespace MeetingApp.Models
{
  public class MeetingInfo
  {
    public int Id { get; set; }
    public string? Location { get; set; }
    public DateTime Date { get; set; }
    public int NumberOfPeople { get; set; }
  }
}

Models/Repository.cs
using System.Net.Http.Headers;

namespace MeetingApp.Models
{
  public class Repository
  {
    static Repository()
    {
      _users.Add(new UserInfo() {Id = 1, Name = "Ali", Email = "abc@gmail.com", Phone = "11111", WillAttend = true });
      _users.Add(new UserInfo() {Id = 2, Name = "Ahmet", Email = "aha@gmail.com", Phone = "144111", WillAttend = false });
      _users.Add(new UserInfo() {Id = 3, Name = "Canan", Email = "cch@gmail.com", Phone = "11211", WillAttend = true });
    }
    private static List<UserInfo> _users = new();
    public static List<UserInfo> Users {
      get{
        return _users;
      }
    }
    public static void CreateUser(UserInfo user)
    {
      user.Id = Users.Count +1;
      _users.Add(user);
    }
    public static UserInfo? GetById(int id)
    {
      return _users.FirstOrDefault(user => user.Id == id);
    }
  }
}

Models/UserInfo.cs
using System.ComponentModel.DataAnnotations;

namespace MeetingApp.Models
{
  public class UserInfo
  {
    public int Id { get; set; }

    [Required(ErrorMessage = "Ad alanı zorunlu!")] //ErrorMessage yazmazsan ing yazılar gelir
    public string? Name { get; set; }

    [Required(ErrorMessage = "Telefon numarası zorunlu!")]
    public string? Phone { get; set; }

    [Required(ErrorMessage = "Eposta adresi zorunlu!")]
    [EmailAddress(ErrorMessage = "Eposta adresi hatalı!")]
    public string? Email { get; set; }

    [Required(ErrorMessage = "Katılım durumu zorunlu!")]
    public bool? WillAttend { get; set; }

    //reuired yalnızca null durum ile karşılaşınca çalışıyor
    //bool lar için default false int için ise 0 dır
    //yani null gelmez
  }
}

Controllers/HomeController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
    public class HomeController: Controller
    {
        public IActionResult Index()
        {
            //int saat = 13;
            int saat = DateTime.Now.Hour;
            //var selamlama = saat > 12 ? "İyi günler" : "Günaydın";
            ViewBag.Selamlama = saat > 12 ? "İyi günler" : "Günaydın";
            int UserCount = Repository.Users.Where(i => i.WillAttend == true).Count();
            //ViewBag.UserName = "Feyza";

            //ViewBag yerine ViewData kullanılabilir
            //ViewData["Selamlama"] = saat > 12 ? "İyi günler" : "Günaydın";
            //ViewData["UserName"] = "Feyza";

            var meetingInfo = new MeetingInfo(){
                Id = 1,
                Location = "İstanbul, Abc Kongre Merkezi",
                Date = new DateTime(2024, 01, 20, 20, 0, 0),
                NumberOfPeople = UserCount
            };

            return View(meetingInfo); //model: selamlama string bir bilgi için gerekli yoksa Viee ismi zannediyor
        }

    }
}

Controllers/MeetingController.cs
using MeetingApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace MeetingApp.Controllers
{
  public class MeetingController: Controller
  {
    [HttpGet]
    public IActionResult Apply()
    {
      return View();
    }
    [HttpPost]
    public IActionResult Apply(UserInfo model)
    {
      //Console.WriteLine($"{Name}\n{Email}\n{Phone}\n{WillAttend}");
      if(ModelState.IsValid){
        Repository.CreateUser(model);
        ViewBag.UserCount = Repository.Users.Where(i => i.WillAttend == true).Count();
        return View("Thanks",model);
      }else {
        return View(model);
      }
    }

    [HttpGet] //get metodu için yazmaya gerek yok çünkü default
    public IActionResult List()
    {
      return View(Repository.Users);
    }
    //meeting/details/idNum
    public IActionResult Details(int id)
    {
      return View(Repository.GetById(id));
    }
  }
}

Views/Home/Index.cshtml
@model MeetingInfo
@{
  ViewBag.Title = "Toplantı Başvuru";
  Layout = "_Layout2";
}
<main class="text-center">
  <!--  atmodel string -->
  <h1 class="h4">@ViewBag.Selamlama</h1> <!--viewbag kullanmazsan atModel demelisin -->
  <!-- View data içinse: ViewData["Selamlama"], ViewData["UserName"] yazardık-->
  <p>Toplantı katılım durumunuzu bildiriniz.</p>
  <div class="card my-2">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">@Model.Location</li>
      <li class="list-group-item">@Model.Date.ToString("dd/MM/yyyy HH:mm:ss") tarihinde gerçekleşecek</li>
      <li class="list-group-item">@Model.NumberOfPeople Katılımcı</li>
    </ul>
  </div>
  <a class="btn btn-sm btn-outline-primary" asp-controller="Meeting" asp-action="Apply" >Başvuru yap</a> <!-- href="/meeting/apply"-->
  <!--asp-controller asp-action çalısşması için view a _ViewImports.cshtml dosyasını eklemeliyiz-->
</main>

Views/Meeting/Apply.cshtml
@model UserInfo
@{
  ViewBag.Title = "Başvuru Formu";
}
<h1 class="text-center">Toplantı Katılım Formu</h1>
<form method="post" action="/Meeting/Apply" novalidate>
  <div asp-validation-summary="All"></div>
  <div class="mb-3">
    <label asp-for="Name" class="form-label">Ad Soyad</label>
    <input asp-for="Name" class="form-control">
  </div>
  <div class="mb-3">
    <label asp-for="Phone" class="form-label">Telefon</label>
    <input asp-for="Phone" class="form-control">
  </div>
  <div class="mb-3">
    <label asp-for="Email" class="form-label">Eposta</label>
    <input asp-for="Email" class="form-control"> <!--type email değil text oldu-->
  </div>
  <div class="mb-3">
    <label asp-for="WillAttend" class="form-label">Katılım Durumu</label>
    <select asp-for="WillAttend" class="form-select">
      <option value="">Seçiniz</option>
      <option value="true">Evet, Geliyorum</option>
      <option value="false">Hayır, Gelmiyorum</option>
    </select>
  </div>
  <button class="btn btn-primary" type="submit">Kaydet</button>
</form>

Views/Meeting/Details.cshtml
@model UserInfo
@{
  ViewBag.Title = "Başvuru Detayı";
}
@{
  var className = @Model.WillAttend == true ? "primary" : "danger"; 
}
<main class="text-center">
  <h1 class="h4">Başvuru Detayı</h1>
  <p>
    <span class="badge text-bg-@className">
      @if(Model.WillAttend == true) {
        <text>Katılıyor</text>
      }else {
        <text>Katılmıyor</text>
      }
    </span>
  </p>
  <p>İsim: @Model.Name</p>
  <p>Email: @Model.Email</p>
  <p>Telefon: @Model.Phone</p>
  <a asp-controller="Meeting" asp-action="List" class="btn btn-outline-@className">Katılımcı Listesi</a>
</main>

Views/Meeting/List.cshtml
@model List<UserInfo>
@{
  ViewBag.Title = "Katılım Listesi";
}
<main class="text-center">
  <h1 class="h4">Toplantı Katılım Listesi</h1>
  <table class="table table-bordered">
    <thead>
      <tr>
        <td>Ad</td>
        <td>Katılım Durumu</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      @{
        int i = 0;
      }
      @foreach (var user in Model) {
        var durum = user.WillAttend == true ? "Evet" : "Hayır";
        var className = user.WillAttend == true ? "table-success" : "table-danger";
        if(user.WillAttend == true)
        {
          i++;
        }
        <tr class="@className">
          <td>@user.Name</td>
          <td>@durum</td>
          <td>
            <a class="btn btn-sm btn-primary" href="/meeting/details/@user.Id">Detay</a>
          </td>
        </tr>
      } 
    </tbody>
  </table>
  <civ class="card">
    <div class="card-body">
      <span>Katılıcı Sayısı: @i</span>
    </div>
  </civ>
</main>

Views/Meeting/Thanks.cshtml
@model UserInfo
@{
  ViewBag.Title = "Başvuru Durumu";
}
<main class="text-center">
  <h1 class="h4">Başvuru Durumu</h1>
  @if(Model.WillAttend == true){
    <p>Teşekkürler @Model.Name. Toplantıya sizinle birlikte @ViewBag.UserCount kişi katılıyor.</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/list">Katılımcıları Listele</a>
  }
  else{
    <p>@Model.Name, katılamadığınız için üzgünüz.</p>
    <a class="btn btn-sm btn-outline-primary" href="/meeting/apply">Başvuru Formu</a>
  }
</main>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
  <link rel="stylesheet" href="/css/styles.css"/>
  <title>@ViewBag.Title - Meeting App</title> <!--Dinamik title bilgisi yerleştirelim-->
</head>
<body>
  <div class="bg-primary text-white p-2 text-center">
    MeetingApp
  </div>
  <div class="container mt-3">
    <div class="row">
      <div class="col-lg-6 mx-auto ">
        <div class="card">
          <div class="card-body">
            @RenderBody()
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>

Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/lib/bootstrap/css/bootstrap.min.css"/>
  <title>@ViewBag.Title - Meeting App</title>
</head>
<body>
  <div class="bg-danger text-white p-2 text-center">
    MeetingApp
  </div>
  <div class="container mt-3">
    <div class="row">
      <div class="col-lg-6 mx-auto text-center">
        <div class="card">
          <div class="card-body">
            @RenderBody()
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>